### ISSUE TITLE
Request for special no OOB class

### ISSUE THREAD

**Issue by Caball009** [j8asic/SpeciaLUT#2]
I love this project, but the template details are a bit over my head to modify it myself. I'd like to request a special class that doesn't allow out-of-bounds access. Whenever a parameter is greater than allowed it should pick the last option / state for this parameter.

Here's an example: https://godbolt.org/z/53b7v6v6s I understand why the code currently doesn't work like this, but I think it could with a new class that functions slightly differently.

**Comment by j8asic** [comment]
Hey thanks. you can already do this since everything is decided in runtime. Do not constrain yourself with function states == variables. One of the possible solution is linked below where I simply introdued a helper that converts `argc` to a function state (0, 1, more than 1):

https://godbolt.org/z/3T4zrMGMr

**Comment by Caball009** [comment]
You're right. I feel a bit silly for asking now. A simple helper function like that should be enough, though I'd argue to make it 'constexpr'. That way the function is only evaluated at compile time and not compiled, I think.

**Comment by j8asic** [comment]
Sure, you can have `constexpr` choosing of states. I'd argue you won't gain much from it since it is (should be) happening on a high level, and the compiler has already _compiled and optimized all_ three possible paths of execution. 
I'm going to close this, but if you have some more questions and suggestions feel free to do so.  
I'll extend the example so the principle does not confuse future users as well.
